=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.9

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AdminApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AdminApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AdminApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdminApi' do
    it 'should create an instance of AdminApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AdminApi)
    end
  end

  # unit tests for post_v1_admin_relevancy
  # Saves search relevancy configuration.
  # Saves search relevancy configuration.
  # @param body Relevancy Configuration
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_admin_relevancy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
