=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.47

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AutocompleteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AutocompleteApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AutocompleteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AutocompleteApi' do
    it 'should create an instance of AutocompleteApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AutocompleteApi)
    end
  end

  # unit tests for get_v1_autocomplete
  # Returns a list of suggestions based on search prefix.
  # Returns a list of suggestions based on search prefix.
  # @param prefix search prefix
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of results to return.
  # @option opts [BOOLEAN] :explain Whether to return explanation of results.
  # @option opts [String] :bucket AB test bucket
  # @return [AutocompleteResponse]
  describe 'get_v1_autocomplete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_autocomplete
  # Returns a list of suggestions based on search prefix.
  # Returns a list of suggestions based on search prefix.
  # @param body Autocomplete Request
  # @param [Hash] opts the optional parameters
  # @return [AutocompleteResponse]
  describe 'post_v1_autocomplete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
