=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.27

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DesignsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DesignsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DesignsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DesignsApi' do
    it 'should create an instance of DesignsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DesignsApi)
    end
  end

  # unit tests for post_v1_similar_designs
  # Returns a list of discoverable designs based on the query of a design&#39;s primary tag.
  # Returns a list of discoverable designs based on the query of a design&#39;s primary tag.
  # @param body Similar Designs Request
  # @param [Hash] opts the optional parameters
  # @return [SimilarDesignsResponse]
  describe 'post_v1_similar_designs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
