=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::LookupApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LookupApi' do
  before do
    # run before each test
    @instance = SwaggerClient::LookupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LookupApi' do
    it 'should create an instance of LookupApi' do
      expect(@instance).to be_instance_of(SwaggerClient::LookupApi)
    end
  end

  # unit tests for get_v1_lookup_by_id
  # Returns a published designs based on id.
  # Returns a published designs based on id.
  # @param design_id id of the design to return
  # @param [Hash] opts the optional parameters
  # @return [Design]
  describe 'get_v1_lookup_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
