=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.13

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RelatedApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RelatedApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RelatedApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RelatedApi' do
    it 'should create an instance of RelatedApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RelatedApi)
    end
  end

  # unit tests for get_v1_related_search
  # Gets related searches based on given term
  # Gets related searches based on given term
  # @param search_term Search term to pull related searches from
  # @param [Hash] opts the optional parameters
  # @return [Array<RelatedResult>]
  describe 'get_v1_related_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
