=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.9

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RelevancyApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RelevancyApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RelevancyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RelevancyApi' do
    it 'should create an instance of RelevancyApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RelevancyApi)
    end
  end

  # unit tests for delete_v1_relevancy_configuration
  # Deletes search relevancy configuration.
  # Deletes search relevancy configuration.
  # @param config_id search relevancy configuration id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v1_relevancy_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_relevancy_configuration
  # Gets a search relevancy configuration.
  # Gets a search relevancy configuration.
  # @param config_id search relevancy configuration id
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_v1_relevancy_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_relevancy_configurations
  # Gets all relevancy configurations.
  # Gets all relevancy configurations.
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_v1_relevancy_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_relevancy_configurations
  # Saves search relevancy configuration.
  # Saves search relevancy configuration.
  # @param body Relevancy Configuration
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_relevancy_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_v1_relevancy_configuration
  # Updates search relevancy configuration.
  # Updates search relevancy configuration.
  # @param config_id search relevancy configuration id
  # @param body Relevancy Configuration
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'put_v1_relevancy_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
