=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.15

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TagSuggestionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TagSuggestionApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TagSuggestionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagSuggestionApi' do
    it 'should create an instance of TagSuggestionApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TagSuggestionApi)
    end
  end

  # unit tests for get_v1_tag_suggestions
  # Returns a list of tag suggestions based on search prefix.
  # Returns a list of tag suggestions based on search prefix.
  # @param prefix search prefix
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of results to return.
  # @option opts [BOOLEAN] :explain Whether to return explanation of results.
  # @return [AutocompleteResponse]
  describe 'get_v1_tag_suggestions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
