=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.38

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TrendingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TrendingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TrendingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TrendingApi' do
    it 'should create an instance of TrendingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TrendingApi)
    end
  end

  # unit tests for get_v1_trending_search
  # Gets trending search results.
  # Gets trending search results.
  # @param [Hash] opts the optional parameters
  # @return [Array<TrendingResult>]
  describe 'get_v1_trending_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_trending_search
  # Saves trending search results.
  # Saves trending search results.
  # @param body Trending search request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_trending_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
