=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.23

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::TagMappingResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TagMappingResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::TagMappingResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagMappingResponse' do
    it 'should create an instance of TagMappingResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::TagMappingResponse)
    end
  end
  describe 'test attribute "child_tag"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "parent_tag"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
