=begin
#TeePublic V3 search Api Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/design'
require 'swagger_client/models/design_slim'
require 'swagger_client/models/es_hit'
require 'swagger_client/models/es_hits'
require 'swagger_client/models/es_lookup_response'
require 'swagger_client/models/es_search_response'
require 'swagger_client/models/explain'
require 'swagger_client/models/search_request'
require 'swagger_client/models/search_response'

# APIs
require 'swagger_client/api/lookup_api'
require 'swagger_client/api/search_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
